### ISSUE TITLE
changing the charge rate

### ISSUE THREAD

**Issue by JulienDidierjean** [geraldoramos/nikola#12]
It would be very nice (I didn't see that anywhere in other app, or mobile app) to be able to change Charge speed (changing the Charge Current) to better plan for charging end-time, etc...

<img width="841" alt="Screen Shot 2019-06-08 at 06 54 06" src="https://user-images.githubusercontent.com/29755854/59146043-42412a00-89ba-11e9-970a-08f9d9826374.png">

**Comment by geraldoramos** [comment]
This would be nice but I don't think this is available through the API:
https://tesla-api.timdorr.com/vehicle/commands/charging
