### ISSUE TITLE
Be able Schedule things (climate on/off, charging, destination) by days and time

### ISSUE THREAD

**Issue by JulienDidierjean** [geraldoramos/nikola#14]
This one could be split into multiple ones I guess
 - Climate Schedule (week days, week end, time, set temp, etc...)
 - Charging schedule (limit, charge rate)
 - program recurrent destination for week days at appropriate Time

**Comment by geraldoramos** [comment]
After thinking about this, it's not possible to implement this without creating a server-side solution. These scheduled tasks must be persisted on a server, therefore the user token would need to be sent to a server. This would disrupt the goal of only communicating with Tesla servers directly. 

Also, maintaining a task service for the releases will cost money and more maintenance, this would require a different model.

I may consider a solution like this if the app grows, let's see. Thanks for your input.
