### ISSUE TITLE
Linux version please

### ISSUE THREAD

**Issue by fmonera** [geraldoramos/nikola#15]
Please, release a Linux installer too.

**Comment by geraldoramos** [comment]
On it! Next release will have it.

**Comment by geraldoramos** [comment]
Linux builds are now available as `deb`, `AppImage` or `zip`.

Please let me know if you find any issues. I tested on Ubuntu using the `deb` version.

**Comment by fmonera** [comment]
Works on Kubuntu 18.10 without problems, thanks.
