### ISSUE TITLE
Icon to exit app

### ISSUE THREAD

**Issue by frankvg** [geraldoramos/nikola#17]
Suggest a standard "x" close button in the top-right to close app instead of having to right-click, and select from drop down.

**Comment by geraldoramos** [comment]
Thanks, will look into that.

Just out of curiosity, what platform are you in @frankvg?

**Comment by frankvg** [comment]
Hi Geraldo,

 

Installed on Windows 10.   

 

I added your app to our Apps of Interest section of TeslaTap.com.  https://teslatap.com/links/#more_apps

 

Really nice work!  I had considered doing something similar (I’m a developer) as I’ve been distrustful of giving up API keys to some unknown server with unknown security. Lack of time and getting old-in-the-tooth programing skills put it on the back burner. Glad you did this!

Best regards,

Frank.

**Comment by geraldoramos** [comment]
Thanks Frank, thats awesome! I'm a mac user so the windows UI is not as tweaked as the mac one. I plan to make it better as the project evolves (and maybe I will find contributors). Maybe for windows I will leave the frame (with close, minimize..) visible. Need to play with it more.

Regards,

Geraldo

**Comment by frankvg** [comment]
Hi Geraldo,

 

The standard Windows frame sounds like a good idea, as it’s standard in most Windows programs. Actually, yours was the first I’ve seen in many years without a frame!  

 

I’m happy to test it out if you need to.

 

My direct email is frank@faqware.com <mailto:frank@faqware.com>  as no need to go through github.

Best regards,

Frank.

**Comment by geraldoramos** [comment]
Thanks Frank! I will play with it for the next release and will send you a version before launch to everybody.
