### ISSUE TITLE
Odometer reading is inaccurate

### ISSUE THREAD

**Issue by Okanagan** [geraldoramos/nikola#19]
I just installed this. Thank you for your work. I have a few suggestions after looking at your application:
1- The odometer reading is off. For me it should show over 8000 km. Instead it shows 5000.
2- The dark background of the location map makes it very hard to see.
3- The charge state is also incorrect. It seems off by 150 km.
4- Consider making the app scaleable. On  a monitor that runs at 2560 x 1440 it is too small and quite hard to read.

I hope this is useful.

**Comment by geraldoramos** [comment]
Thanks a lot for the feedback.

1) Bug detected, Tesla API seems to return the odometer value always in miles, regardless of the preference of the user. I will need to convert in the UI. Expect this to be fixed on the next release, maybe still tonight.
2) Noted.
3) Same issue as 1.
4) Noted

**Comment by geraldoramos** [comment]
Issue 1/3 has been fixed in the last release (0.27). Can you validate @Okanagan ? To update, just restart the app and it will check for a new version and download, then, restart again to have it installed.

For 3 and 4, it will become a card in my Todo list to further exploration.

Thanks!

**Comment by Okanagan** [comment]
Hi Geraldo,

 

Yep, now it shows the correct information.

 

I still think the background is too dark, particularly since Model 3 is black as well. Tesla_app-1 is the way it looks on my screen, the other has a brighter version of the map. Just to illustrate my point.

 

Thanks again for your work,

Denys

**Comment by geraldoramos** [comment]
I can't see the images, can you try to post from [here](https://github.com/geraldoramos/nikola/issues/19) as opposed to replying the email? 

Thanks for your feedback, I got that the UI might be not optimum for some configurations, I will try to tweak it to make it more readable.

**Comment by Okanagan** [comment]
Sorry, I'm new to this...
![Tesla_app-1](https://user-images.githubusercontent.com/51684793/59293446-17620a80-8c34-11e9-833e-2fdaca42923d.jpg)
![Tesla_app-2](https://user-images.githubusercontent.com/51684793/59293447-17620a80-8c34-11e9-80e2-3ca84f203fc0.jpg)

**Comment by geraldoramos** [comment]
Thanks! I will tweak the map colors in the next release.

**Comment by Okanagan** [comment]
I'm pretty good with Photoshop. If you need different colour Model 3s, let me know I'll be happy to send them to you.
