### ISSUE TITLE
Please support more than one car

### ISSUE THREAD

**Issue by NikolaiSa** [geraldoramos/nikola#23]
It looks like the app currently only supports one car. Please make it support multiple.

**Comment by geraldoramos** [comment]
hey @NikolaiSa, yes, It currently just support one car. The ability to support multiple is on my To-Do.

Question: Did it work for you and pulled one of the cars or the app crashed?

**Comment by NikolaiSa** [comment]
It works great but only for the 2nd car. I'm happy to test it once you have something (I have 2 cars on my account).

**Comment by geraldoramos** [comment]
Gotcha, I will ping you here once I have this released.

**Comment by traviscollins** [comment]
When you do implement this, it would be awesome if the map showed all vehicles at one time. Allow the user to select the vehicle shown above by clicking on the map icons.
