### ISSUE TITLE
Request: Customize icon to show two selectable pieces of info

### ISSUE THREAD

**Issue by bradhs** [geraldoramos/nikola#24]
Ability to customize icon to show two selectable pieces of info.

For example, TEMP/MILES.

**Comment by geraldoramos** [comment]
You mean the tray icon? I've been debating about this with other user.

Here is my response:

```
The application stops polling data from Tesla servers if the main window is not visible. In order to have updated data in the tray, we would need to keep polling continuously and this would prevent the car to sleep and could affect battery consumption.

Here is how it currently works:

Data updates every 10s if the main window is visible
Data updates immediately when the main window is opened.
```

Let me know what you think and if it makes sense.

**Comment by bradhs** [comment]
I see the issue, I wouldn't want my car constantly polling.   Maybe a customizable polling interval in minutes?  For example, I could say poll every 60 minutes.  60 minutes sounds reasonable to me.

Also, I'd not want the app to wake up my computer to poll.

**Comment by geraldoramos** [comment]
I will look into that, for now, it does not poll if inactive, it only makes sense to poll every 60min if we need the data for something (If it's not fresh enough, maybe the tray showing battery/miles information is not super useful).

Will think about that, thanks a lot for your feedback.
