### ISSUE TITLE
Unable to open window after some time

### ISSUE THREAD

**Issue by bradhs** [geraldoramos/nikola#26]
I have two issues to report.  After a while of the app running I can no longer get the window to open to view my car stats. Watch the attached video.  

Also, in the video: When I switch to a different desktop and click the icon to view my Tesla status the Mac will switch to desktop 1--which is where the app started.  I think there's a setting somewhere that says to allow the window on all desktops.

**Comment by bradhs** [comment]
[Screen Recording 2019-06-13 at 06.14.16.mov.zip](https://github.com/geraldoramos/nikola/files/3286568/Screen.Recording.2019-06-13.at.06.14.16.mov.zip)
Video attached.

**Comment by geraldoramos** [comment]
Can you please update to the last version? This is supposed to be fixed on `0.2.9`

To update, first kill the app by going to `Active Monitor` on your mac, search for `nikola` and kill it. Then reopen the app. It should show a notification that the last version was downloaded, then restart the app and you should have `0.2.9`. If it doesn't work, try manually [downloading](https://github.com/geraldoramos/nikola/releases/latest) again

Let me know if you are still having the issue or if this happened in the last version.

**Comment by geraldoramos** [comment]
Sorry, regarding issue 2 (multi-desktop support), I will look into that.

**Comment by geraldoramos** [comment]
This issue is not resolved, but I will keep [this issue](https://github.com/geraldoramos/nikola/issues/28) opened instead of this one here.
