### ISSUE TITLE
right click menu

### ISSUE THREAD

**Issue by EsenbekAliev** [geraldoramos/nikola#32]
I don't see log out option, right click on top bar icon does nothing.

**Comment by EsenbekAliev** [comment]
Another "issue", "new version downloaded and will be installed after exit" pop up message is keep popping up every ~5 minutes, not sure how to exit the app and install it, I could kill the process I guess, but pretty sure not the best way :) 
 FIY I already have the newest version from the site, but still keep getting the message.

**Comment by EsenbekAliev** [comment]
I'm on Mac 10.14.5

**Comment by geraldoramos** [comment]
I released 2 versions really close to each other (0.3.1 and 0.3.2). Sorry about that.

Regarding the version, you should click inside the window, did you try this?
![image](https://user-images.githubusercontent.com/5693297/59922782-c352e500-93ee-11e9-81cf-a8943ef3e08c.png)

**Comment by EsenbekAliev** [comment]
ah, I see, it was just weird when nothing happens when you click on icon :D
