### ISSUE TITLE
show charging status

### ISSUE THREAD

**Issue by DemiVis** [geraldoramos/nikola#34]
would be nice to show charging status when polled, maybe as an option. I typically charge at work and it would be nice to check in and see how it's going, or even an indication that it is at least still going at all, with a quick click on your wonderful app

**Comment by geraldoramos** [comment]
Did you try to hover on top of the car image? Maybe it's not clear enough that this is possible...

![image](https://user-images.githubusercontent.com/5693297/60549336-ce0c5480-9ce1-11e9-9b0b-91aa4b7f4fa8.png)
