### ISSUE TITLE
Temperature is showing wrong unit

### ISSUE THREAD

**Issue by chriscardinal** [geraldoramos/nikola#4]
First, this app looks great, well done! A welcome successor to the no-longer-maintained VisibleTesla.

The temperature is showing Celsius, but with an F:

![image](https://user-images.githubusercontent.com/327877/59134586-8982d880-8930-11e9-8811-ed7742a0cf8c.png)

Doesn't appear to be a way to change the units, either.

**Comment by geraldoramos** [comment]
Good call, forgot to handle that. I will fix it in the next release. Auto-update should be working fine so you should get an alert once a new version is available, it should be soon.

**Comment by geraldoramos** [comment]
So, looks like the API always returns celsius and it doesn't tell which scale it uses, so I assume that it's always Celsius. In the future we can maybe do a converter in the UI and make a toggle, but not sure how important it is. I've changed from `F` to `C` in the UI and this should be in the next release. Thanks for catching this @chriscardinal.

**Comment by jbenamy** [comment]
I unfortunately would not use the app if the units were stuck in metric.  Please have option to convert to Fahrenheit.

**Comment by geraldoramos** [comment]
@jbenamy this has been fixed in the last release. Please download `0.2.6`.
